name: get source code

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]



jobs:

  # https://media.codeweavers.com/pub/crossover/source/crossover-sources-21.1.0.tar.gz
  source-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh git@github.com || true

      - run: git config --global user.email ${{ secrets.git_email }}
      - run: git config --global user.name ${{ secrets.git_name }}

      - run: python3 -m pip install -U -r ./.github/workflows/requirements.txt

      - name: Download latest
        run: python3 ./.github/workflows/crossover-sources.py

      - run: echo NAME=$(jq -r .name *.json) >>${GITHUB_ENV}
      - run: echo VER=$(jq -r .version *.json) >>${GITHUB_ENV}
      - run: echo URL=$(jq -r .url *.json) >>${GITHUB_ENV}

      - run: mkdir source
      - run: mv -v "${{ env.NAME }}" source
      - run: mv -v "${{ env.NAME }}.json" source
      - run: mv -v source /tmp

      - run: git clean -xdf
      - run: git branch -f ${{ env.VER }} || git checkout ${{ env.VER }}

      - name: copy latest
        run: tar -zxf /tmp/source/${{ env.NAME }} -C /tmp/source
      - run: rsync -arvh --delete /tmp/source/*/* .

      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.GIT_SSH }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "latest changes ${{ env.VER }} ${{ env.NAME }} ${{ env.URL }}"

      - name: push branch
        run: git push origin HEAD:${{ env.VER }}

      - name: checkout master
        run: git checkout master

      - name: fetch from master
        run: git fetch origin master

      - name: merge into master
        run: git merge ${{ env.VER }}

      - name: push code to master
        run: git push origin HEAD:master