name: get source code

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]



jobs:

  # https://media.codeweavers.com/pub/crossover/source/crossover-sources-21.1.0.tar.gz
  source-code:

    steps:
      - uses: actions/checkout@v1

      - run: python3 -m pip install -U -r ./.github/workflows/requirements.txt

      - name: Download latest
        run: python3 ./.github/workflows/crossover-sources.py

      - run: mkdir source
      - run: mv *.tar.gz source
      - run: mv *.json source
      - run: mv source /tmp
      - run: mkdir -p /tmp/source/extracted
      - run: tar -zxf /tmp/source/*.tar.gz -C /tmp/source/extracted
      - run: rsync -arvh --delete /tmp/source/extracted/*/* .

      - run: which jq

      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.git_ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "latest changes"
      - name: fetch from master
        run: git fetch origin master
      - name: push code to master
        run: git push origin HEAD:master

